version: '3.8'

services:
  allele-bot:
    build: .
    container_name: allele_engine
    restart: always
    volumes:
      - ./.allele:/app/.allele
    ports:
      - "8081:8081"

  ui:
    build: 
      context: ./ui
      dockerfile: Containerfile
    container_name: allele_ui
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - allele-bot
